#ifndef CONFIG_H
#define CONFIG_H

// 0x3 ESP Project Configuration
// Generated by setup script on Sat Sep 13 16:02:49 WIB 2025

// Project Information
#define PROJECT_NAME "ada-1"
#define PROJECT_VERSION "1.0.0"
#define PROJECT_AUTHOR "TirtaPatriot"

// WiFi Configuration
#define WIFI_TIMEOUT 30000          // 30 seconds
#define WIFI_RETRY_DELAY 5000       // 5 seconds
#define AP_PASSWORD "Perjuangan#99"
#define CONFIG_PORTAL_TIMEOUT 300   // 5 minutes

// OTA Configuration
#define OTA_USERNAME "admin"
#define OTA_PASSWORD "Mar9aMulya"
#define OTA_PORT 8080

// Web Server Configuration
#define WEB_SERVER_PORT 80

// Hardware Configuration
#ifndef LED_BUILTIN
#define LED_BUILTIN 2        // Built-in LED pin for status indication
#endif
#define STATUS_LED_PIN LED_BUILTIN

// Debug Configuration
#define DEBUG_ENABLED true
#define DEBUG_BAUD_RATE 115200

// Network Configuration
#define HOSTNAME "ada-1"

// Timing Configuration
#define HEARTBEAT_INTERVAL 30000    // 30 seconds
#define STATUS_UPDATE_INTERVAL 5000 // 5 seconds

#endif // CONFIG_H
