#ifndef CONFIG_H
#define CONFIG_H

// 0x3 ESP Project Configuration
// Generated by setup script on Sat Sep 13 16:02:49 WIB 2025

// Project Information
#define PROJECT_NAME "ada-1"
#define PROJECT_VERSION "1.0.0"
#define PROJECT_AUTHOR "TirtaPatriot"

// WiFi Configuration
#define WIFI_TIMEOUT 30000          // 30 seconds
#define WIFI_RETRY_DELAY 5000       // 5 seconds
#define AP_PASSWORD "Perjuangan#99"
#define CONFIG_PORTAL_TIMEOUT 300   // 5 minutes

// OTA Configuration
#define OTA_USERNAME "admin"
#define OTA_PASSWORD "Mar9aMulya"
#define OTA_PORT 8080

// Auto-Update Configuration
#define AUTO_UPDATE_ENABLED true                    // Enable auto-update by default
#define AUTO_UPDATE_SERVER_URL "https://your-server.com/firmware"  // Default update server
#define AUTO_UPDATE_CHECK_INTERVAL 3600000         // Check every 1 hour (3600000 ms)
#define AUTO_UPDATE_VERSION_ENDPOINT "/version"    // Version check endpoint
#define AUTO_UPDATE_FIRMWARE_ENDPOINT "/download"  // Firmware download endpoint
#define AUTO_UPDATE_MAX_RETRY 3                    // Maximum retry attempts
#define AUTO_UPDATE_RETRY_DELAY 300000             // 5 minutes retry delay

// Web Server Configuration
#define WEB_SERVER_PORT 80

// Hardware Configuration
#ifndef LED_BUILTIN
#define LED_BUILTIN 2        // Built-in LED pin for status indication
#endif
#define STATUS_LED_PIN LED_BUILTIN

// Debug Configuration
#define DEBUG_ENABLED true
#define DEBUG_BAUD_RATE 115200

// Network Configuration
#define HOSTNAME "ada-1"

// Modbus Configuration
#define MODBUS_SLAVE_ADDRESS 2      // Board ada-1 Modbus slave address
#define MODBUS_BAUD_RATE 9600       // Default baud rate
#define MODBUS_ENABLE_SLAVE true    // Enable Modbus slave functionality

// Timing Configuration
#define HEARTBEAT_INTERVAL 30000    // 30 seconds

// Health Monitoring Configuration
#define SYSTEM_HEALTH_CHECK_INTERVAL 5000  // 5 seconds

// Module Health Status
enum ModuleHealth {
    HEALTH_OK = 0,
    HEALTH_WARNING = 1,
    HEALTH_ERROR = 2,
    HEALTH_UNKNOWN = 3
};

// System Health Structure
struct SystemHealthStatus {
    ModuleHealth wifi = HEALTH_UNKNOWN;
    ModuleHealth modbus = HEALTH_UNKNOWN;
    ModuleHealth webserver = HEALTH_UNKNOWN;
    ModuleHealth sd = HEALTH_UNKNOWN;
    ModuleHealth ntp = HEALTH_UNKNOWN;
    ModuleHealth ota = HEALTH_UNKNOWN;
    ModuleHealth analytics = HEALTH_UNKNOWN;
    ModuleHealth diagnostics = HEALTH_UNKNOWN;
    unsigned long lastHealthCheck = 0;
    bool systemHealthy = false;
};

#endif // CONFIG_H
